### ISSUE TITLE
Risikooversikt virker ikke etter oppgradering til 1.8 versjonen

### ISSUE THREAD

**Issue by Rnjarh** [Puzzlepart/prosjektportalen365#1050]
### Beskriv feilen

Får opp følgende feilkode når jeg åpner Risikooversikt på Porteføljenivå:

Noe gikk galt
Hvis problemet vedvarer, kontakter du administratoren og gi dem informasjonen i Teknisk informasjon.
TEKNISK INFORMASJON
FEIL:
Finner ikke angitt visning.

KALLSTAKK:
Error: Finner ikke angitt visning.
at new t (https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2373982)
at t.<computed> (https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2426086)
at https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2496635
at produce (https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2587008)
at https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2496613
at Array.reduce (<anonymous>)
at https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2496496
at Object.$r [as useReducer] (https://res-1.cdn.office.net/files/sp-client/react-dom-16-bundle_none_8eaea77e9a62cc734837.js:2:65594)
at t.useReducer (https://res-1.cdn.office.net/files/sp-client/react-16-bundle_none_30207a65b736600f4c92.js:2:7062)
at https://publiccdn.sharepointonline.com/customer.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_cecd29036bdb1c71a5c2.js:2:2428382

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Porteføljenivå
 2. Risikooversikt
 

### Forventet oppførsel

Forventet at risikooversikten fungerte på samme måte som ved de tidligere versjonen 

### Hvilke nettleser(e) oppleves feilen på?

Chrome, Microsoft Edge

### Versjon

1.8.0

**Comment by Remi749** [comment]
Hei @Rnjarh ,
etter 1.8.0 har 'Risikooversikt' blitt omdøpt til 'Usikkerhetoversikt'. Kan du sjekke områdesider og se om du kanskje har liggende den gamle siden. Prøv så å gå inn på `SitePages/Usikkerhetsoversikt.aspx`

**Comment by Rnjarh** [comment]
Du hadde rett. Fant siden "Usikkerhetsoversikt under områdesider. Har endret menyen og alt fungerer som som forventet. Takk for hjelpen.

**Comment by Remi749** [comment]
Godt å høre!
