### ISSUE TITLE
Feilmelding i prosjektinformasjon

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#1086]
### Beskriv feilen

En feil oppstår en sjelden gang i prosjektinformasjon. Feilmeldingen i console tyder på at det er en feil som er relatert til localstorage. I network-taben viser forespørsel mot https://xxx.sharepoint.com/sites/prosjektportalen/_api/web/lists/getByTitle('Prosjektstatus')/items?$filter=(GtSiteId%20eq%20%27f4c80fe2-1e1b-4715-9983-a7628df4e362%27)%20and%20GtModerationStatus%20eq%20%27Publisert%27&$expand=FieldValuesAsText,AttachmentFiles&$orderby= en størrelse på 1.3 MB.

### Hvordan reprodusere feilen

Usikker på hvordan gjenskape. Må prøve å dytte masse greier inn i statusrapporten.

Kan feilsøkes på prosjekt PP-ae260 hos kunde xxx.

### Forventet oppførsel

Feilen bør håndteres og ingen feil bør vises brukere.

### Skjermbilder

![image](https://user-images.githubusercontent.com/1837390/232749018-63d01c8d-58ec-443e-9d49-e796a8fd0e04.png)

### Ytterligere informasjon

Bør vi skrive om caching til å gå mot IndexedDB? https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API/Using_IndexedDB

### Hvilke nettleser(e) oppleves feilen på?

Microsoft Edge

### Versjon

1.8.0

### Relevant logg

```shell
Message: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/prosjektportalen/_api/web/lists/getbytitle('prosjektstatus')/items?$filter=(gtsiteid eq 'f4c80fe2-1e1b-4715-9983-a7628df4e362') and gtmoderationstatus eq 'publisert'&$expand=fieldvaluesastext,attachmentfiles&$orderby=id desc' exceeded the quota. Data: {"stack":"Error: Failed to execute 'setItem' on 'Storage': Setting the value of 'https://xxx.sharepoint.com/sites/prosjektportalen/_api/web/lists/getbytitle('prosjektstatus')/items?$filter=(gtsiteid eq 'f4c80fe2-1e1b-4715-9983-a7628df4e362') and gtmoderationstatus eq 'publisert'&$expand=fieldvaluesastext,attachmentfiles&$orderby=id desc' exceeded the quota.\n    at e.put (https://xxx.sharepoint.com/sites/appcatalog/ClientSideAssets/b69cb2f2-762d-425d-8e0b-d59c08918831/project-information-web-part_81c1efadb57216c10e1a.js:2:138942)\n    at e.cacheData (https://xxx.sharepoint.com/sites/appcatalog/ClientSideAssets/b69cb2f2-762d-425d-8e0b-d59c08918831/project-information-web-part_81c1efadb57216c10e1a.js:2:458013)\n    at https://xxx.sharepoint.com/sites/appcatalog/ClientSideAssets/b69cb2f2-762d-425d-8e0b-d59c08918831/project-information-web-part_81c1efadb57216c10e1a.js:2:457900"}
e.log @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
e.log @ project-information-web-part_81c1efadb57216c10e1a.js:2
e.error @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
Promise.catch (async)
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
Promise.then (async)
e.reqImpl @ project-information-web-part_81c1efadb57216c10e1a.js:2
t.reqImpl @ project-information-web-part_81c1efadb57216c10e1a.js:2
e.getCore @ project-information-web-part_81c1efadb57216c10e1a.js:2
t.getCore @ project-information-web-part_81c1efadb57216c10e1a.js:2
t.get @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
m @ project-information-web-part_81c1efadb57216c10e1a.js:2
e.getStatusReports @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
zs @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
(anonymous) @ project-information-web-part_81c1efadb57216c10e1a.js:2
os @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
yc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
vc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
ac @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
(anonymous) @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.unstable_runWithPriority @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Gi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
qi @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
rc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
Wc @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.render @ react-dom-16-bundle_none_c677b08c440c9638b562.js:2
t.renderComponent @ project-information-web-part_81c1efadb57216c10e1a.js:2
t.render @ project-information-web-part_81c1efadb57216c10e1a.js:2
t._renderWithAccessibleTitle @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
t._onInViewport @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._internalFirstTimeRender @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e._renderWebPart @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
e.loadWebPart @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
ms @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Lc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Ki @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Ac @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
hc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Ki @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Qi @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
qi @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
gc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
ad @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
t.render @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
t._renderSingleCanvasCore @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._renderCanvas @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._tryRenderSingleCanvas @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._tryRenderCanvas @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
a._onFieldsLoad @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
f @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e.processAction @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e.dispatch @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._endInitialize @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
t.componentDidMount @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t.componentDidMount @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
ms @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Lc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
IKDZ.t.unstable_runWithPriority @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Ki @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Ac @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
hc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
uc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
Xc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
gc @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
ad @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
t.render @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:69
t.onRender @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._renderCoreRouter @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t.onRender @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._onRender @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
t._render @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
e._initializeApplication @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e._initializeApplicationWithTelemetry @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e.startApplication @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e.navigate @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e.navigateToApplication @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
c @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
s @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e._startApplication @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
e._startApplication @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
(anonymous) @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
Promise.then (async)
e.start @ sp-pages-assembly_nb-no_843187f99cf782532518e2a8eb4b68ca.js:70
loaderStart @ ProjectHome.aspx?sw=bypass:97
startSpfx @ ProjectHome.aspx?sw=bypass:109
(anonymous) @ ProjectHome.aspx?sw=bypass:136
(anonymous) @ ProjectHome.aspx?sw=bypass:140
```

**Comment by tarjeieo** [comment]
Overskriften på Prosjektstatus oppsummeringen kan også være klikkbar og gå til Prosjektstatus
