### ISSUE TITLE
Installation: Error creating list 'Prosjekter'

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#131]
#### Category

[ ] Enhancement

[x] Bug

[ ] Question

#### Browser

N/A

#### Summary

```powershell
powershell.exe Information: 0 : 2019-10-10 14:07:18.9702	[List instances]	[10]	[Debug]	Creating list Prosjekter failed: Value does not fall within the expected range. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ConfigureContentTypes(Web web, List list, ListInstance templateList, Boolean isNewList, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	4979ms	b0e04dfa-5640-4a90-9018-9c50c671ef81
```

#### Version

1.0.4

**Comment by olemp** [comment]
Closed as cannot reproduce.

**Comment by tarjeieo** [comment]
Got this exact error today on a new install of PP365.

```PowerShell
powershell.exe Information: 0 : 2020-03-26 15:43:02.2002	[List instances]	[10]	[Debug]	Creating list Prosjekter	3137ms	a1b22693-2606-42a9-9823-e9493fe83bd2
powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[List instances]	[10]	[Debug]	Creating list Prosjekter failed: Value does not fall within the expected range. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ConfigureContentTypes(Web web, List list, ListInstance templateList, Boolean isNewList, PnPMonitoredScope scope)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
   at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	5885ms	a1b22693-2606-42a9-9823-e9493fe83bd2
powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[List instances]	[10]	[Debug]	Code execution scope ended	5885ms	a1b22693-2606-42a9-9823-e9493fe83bd2
powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[ProvisioningTemplate WebHook Call]	[10]	[Debug]	Code execution scope started	0ms	a1b22693-2606-42a9-9823-e9493fe83bd2
powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[ProvisioningTemplate WebHook Call]	[10]	[Debug]	Code execution scope ended	0ms	a1b22693-2606-42a9-9823-e9493fe83bd2
powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[Provisioning]	[10]	[Debug]	Code execution scope ended	369770ms	a1b22693-2606-42a9-9823-e9493fe83bd2
```

**Comment by olemp** [comment]
> Got this exact error today on a new install of PP365. Attempted to install PP365 1.2.0 with latest PnP PowerShell 3.12.2003.0
> 
> ```powershell
> powershell.exe Information: 0 : 2020-03-26 15:43:02.2002	[List instances]	[10]	[Debug]	Creating list Prosjekter	3137ms	a1b22693-2606-42a9-9823-e9493fe83bd2
> powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[List instances]	[10]	[Debug]	Creating list Prosjekter failed: Value does not fall within the expected range. :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
>    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
>    at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
>    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ConfigureContentTypes(Web web, List list, ListInstance templateList, Boolean isNewList, PnPMonitoredScope scope)
>    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateList(Web web, ListInstance templateList, TokenParser parser, PnPMonitoredScope scope, Boolean isNoScriptSite)
>    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)	5885ms	a1b22693-2606-42a9-9823-e9493fe83bd2
> powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[List instances]	[10]	[Debug]	Code execution scope ended	5885ms	a1b22693-2606-42a9-9823-e9493fe83bd2
> powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[ProvisioningTemplate WebHook Call]	[10]	[Debug]	Code execution scope started	0ms	a1b22693-2606-42a9-9823-e9493fe83bd2
> powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[ProvisioningTemplate WebHook Call]	[10]	[Debug]	Code execution scope ended	0ms	a1b22693-2606-42a9-9823-e9493fe83bd2
> powershell.exe Information: 0 : 2020-03-26 15:43:04.9478	[Provisioning]	[10]	[Debug]	Code execution scope ended	369770ms	a1b22693-2606-42a9-9823-e9493fe83bd2
> ```

This is 95% due to the current CSOM issues. They really need to show a better error message than _Value does not fall within the expected range_.

**Comment by tarjeieo** [comment]
Could be, but it's failing on the same list multiple times (multiple installations)

**Comment by tarjeieo** [comment]
But I cannot reproduce...

**Comment by olemp** [comment]
> Could be, but it's failing on the same list multiple times (multiple installations)

I once I had to rerun the install script 6 times

**Comment by olemp** [comment]
If it was something wrong with the list, I'm sure you would be able to reproduce?

**Comment by tarjeieo** [comment]
Yeah, works on subsequent tries with latest PnP. Weird that it's failing on the same list multiple times though... Anyway - closing (again)
