### ISSUE TITLE
Programstatus laster ikke: Cannot read properties of undefined (reading 'manualConfigurationPath')

### ISSUE THREAD

**Issue by olemp** [Puzzlepart/prosjektportalen365#1318]
### Beskriv feilen

Noe gikk galt
Hvis problemet vedvarer, kontakter du administratoren og gi dem informasjonen i Teknisk informasjon.
TEKNISK INFORMASJON
FEIL:
Cannot read properties of undefined (reading 'manualConfigurationPath')

KALLSTAKK:
TypeError: Cannot read properties of undefined (reading 'manualConfigurationPath')
    at t.render (https://publiccdn.sharepointonline.com/puzzlepart.sharepoint.com/sites/appcatalog/ClientSideAssets/99305c90-4fdb-4289-9379-2702957b3777/project-status-web-part_8e4bada8b133aaa5323f.js:2:1999477)
    at t._renderWithAccessibleTitle (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_36387956803cad44f7ce49ffec2389f4.js:79:534523)
    at https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_36387956803cad44f7ce49ffec2389f4.js:79:533977

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til [Programstatus](https://puzzlepart.sharepoint.com/sites/OsloProgramfortjenesteinnovasjon/SitePages/Status.aspx)

### Forventet oppførsel

At programstatus laster OK.

### Skjermbilder

![image](https://github.com/Puzzlepart/prosjektportalen365/assets/7606007/f8df42c4-3262-48d8-9b62-85a0a93b8b64)

### Versjon

1.9.0 (preview)

**Comment by olemp** [comment]
Løst i https://github.com/Puzzlepart/prosjektportalen365/commit/8d8ebe2dabb2b637258c5d0b087f161442463472
