### ISSUE TITLE
Failed to apply PnP Portfolio template (Fresh installation with v1.10.0) 

### ISSUE THREAD

**Issue by prathapkumarsalian** [Puzzlepart/prosjektportalen365#1571]
### Beskriv feilen

/sites/PP365/Lists/Idebehandling Check the formula for spelling mistakes or change the non-existing column to an existing column.

pwsh Error: 0 : 2024-10-09 12:31:13.8969	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: /sites/P365/Lists/Idebehandling : The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column.

   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -2146232832
ServerErrorTypeName: Microsoft.SharePoint.SPException
ServerErrorTraceCorrelationId: 203058a1-10bc-a000-2ac5-25a536a96eff
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
pwsh Error: 0 : 2024-10-09 12:31:13.8976	[Fields]	[16]	[Error]	Updating field {ce451f2c-a098-48ba-a8a5-d1d4ffc225d6} failed: /sites/P365/Lists/Idebehandling : The formula refers to a column that does not exist.  Check the formula for spelling mistakes or change the non-existing column to an existing column.
 :    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)

### Hvordan reprodusere feilen

Trinn for å gjenskape:

 1. Gå til ...
 2. Klikk på ...
 3. Scroll ned til ...
 4. Se feil

### Skjermbilder

![image](https://github.com/user-attachments/assets/7ab05b5c-24ec-4a09-9534-a2cbc5fadc33)

### Versjon

1.8.x (forrige stabile)

**Comment by tarjeieo** [comment]
Kom du videre @prathapkumarsalian? Har du brukt idebehandling-lista fra før? Om ikke så kan du jo prøve å slette den før du prøver igjen..

**Comment by Remi749** [comment]
Lukker denne pga inaktivitet. Dersom det er aktuelt igjen så kan du gjenåpne @prathapkumarsalian
