### ISSUE TITLE
Resource allocation does not work in IE11

### ISSUE THREAD

**Issue by tarjeieo** [Puzzlepart/prosjektportalen365#166]
**Describe the bug**
Web part doesnt load with error:

On another IE instance I got "Objektet støtter ikke egenskapen eller metoden getOwnPropertyDescriptors". 

This error is about certificates for some reason - but suspect it will be fixed by using polyfills on the page?

Noe gikk galt
Hvis problemet vedvarer, kontakter du administratoren og gi dem informasjonen i Teknisk informasjon.
Teknisk informasjon

[SPLoaderError.loadComponentError]:
Failed to load component "2ef269b2-6370-4841-8b35-2185b7ccb22a" (ResourceAllocationWebPart). Original error: Failed to load URL 'https://publiccdn.sharepointonline.com/pzlcloud.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/resource-allocation-web-part_6e3f15a98629190bae092de01894a6b2.js' for resource 'resource-allocation-web-part' in component '2ef269b2-6370-4841-8b35-2185b7ccb22a' (ResourceAllocationWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.

INNERERROR:
Failed to load URL 'https://publiccdn.sharepointonline.com/pzlcloud.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/resource-allocation-web-part_6e3f15a98629190bae092de01894a6b2.js' for resource 'resource-allocation-web-part' in component '2ef269b2-6370-4841-8b35-2185b7ccb22a' (ResourceAllocationWebPart). There was a network problem. This may be a problem with a HTTPS certificate. Make sure you have the right certificate.
CALLSTACK:
Error
   at t._generateErrorStackForIE (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:4:53963)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:4:53499)
   at t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:20:118832)
   at e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:20:128525)
   at e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:20:124550)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:20:115044)
   at Anonymous function (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:1:16156)
   at F (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:1:16132)
   at C (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:1:15977)
   at B (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_nb-no_05577a3b67632f7dc4b858e4ccd171e4.js:1:15565)

Version 1.1.6

**Comment by olemp** [comment]
Hmmm, I thought we included polyfills already. Maybe not for this one.

https://www.google.com/search?q=getownpropertydescriptors+polyfill&oq=getOwnPropertyDescriptors&aqs=chrome.1.69i57j0l7.2567j0j7&sourceid=chrome&ie=UTF-8

**Comment by olemp** [comment]
Can't figure out where we're using it. 

All I can see is this in the `pnpm-lock.yaml` files.

```
  /util.promisify/1.0.0:
    dependencies:
      define-properties: 1.1.3
      object.getownpropertydescriptors: 2.0.3
```

**Comment by JimmyHang** [comment]
The presentation of reason is weird:

![image](https://user-images.githubusercontent.com/18226765/70747214-cb4d6b00-1d27-11ea-87e4-3851acdeeef6.png)

**Comment by olemp** [comment]
@JimmyHang https://github.com/Puzzlepart/prosjektportalen365/commit/3bada7d1ff0ea4a1e8f7dd6df28703d2836eea52

You can manually fix this by editing the site field on the hub site, and on the project sites.

**Comment by JimmyHang** [comment]
Thanks @olemp, looks good now, I fixed the field, but it took some time before it got updated. Are the webparts using the search index to present content or??

**Comment by olemp** [comment]
Yes!
