### ISSUE TITLE
Erfaringslogg vises ikke - cannot read properties of null

### ISSUE THREAD

**Issue by OleKrNaes** [Puzzlepart/prosjektportalen365#754]
Vi har nylig oppgradert til versjon 1.6.1 av prosjektportalen. Når vi velger "Erfaringslogg" (i toppmenyen) får vi følgende feilmelding:

FEIL:
Cannot read properties of null (reading 'views')

KALLSTAKK:
TypeError: Cannot read properties of null (reading 'views')
at ds (https://publiccdn.sharepointonline.com/vtfk.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_0ca30757d3f3703e7602.js:1:1951665)
at https://publiccdn.sharepointonline.com/vtfk.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_0ca30757d3f3703e7602.js:1:1993500
at https://publiccdn.sharepointonline.com/vtfk.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_0ca30757d3f3703e7602.js:1:1999500
at Object.useMemo (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_3113cb2814aaa05d577d29d01906dee4.js:69:68784)
at t.useMemo (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_3113cb2814aaa05d577d29d01906dee4.js:3:6951)
at Dc (https://publiccdn.sharepointonline.com/vtfk.sharepoint.com/sites/appcatalog/ClientSideAssets/00483367-68e2-4977-9cc3-6cf0de623daa/portfolio-aggregation-web-part_0ca30757d3f3703e7602.js:1:1992548)
at Yr (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_3113cb2814aaa05d577d29d01906dee4.js:69:63936)
at ys (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_3113cb2814aaa05d577d29d01906dee4.js:69:109823)
at pc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_3113cb2814aaa05d577d29d01906dee4.js:69:102601)
at uc (https://res-1.cdn.office.net/files/sp-client/sp-pages-assembly_nb-no_3113cb2814aaa05d577d29d01906dee4.js:69:102526)

**Comment by Remi749** [comment]
@OleKrNaes, thanks for reporting this. This is a known bug which we are currently working on. I will send you a script that will fix this bug when it's complete.

**Comment by Remi749** [comment]
@OleKrNaes, this will now be fixed automatically when upgrading to 1.7.0 after release.
